echo "This code does not perform a specific action"
echo ""
echo "You must folow these instructions:"
echo ""
echo "1. Edit the file stable-diffusion-web-ui/launch.py"
echo ""
echo "2. Locate the following line of code:"
echo "commandline_args = os.environ.get('COMMANDLINE_ARGS', "")"
echo ""
echo "3. Replace that line with this line of code:"
echo "commandline_args = os.environ.get('COMMANDLINE_ARGS', """--skip-torch-cuda-test --opt-sdp-attention --precision full --no-half""")"
echo ""
echo "4. Save and commit the file"
echo ""
echo "Run the next shell file in this series."
